package com.siva.taskTracker.repository;

import com.siva.taskTracker.entity.Team;
import com.siva.taskTracker.entity.TeamMember;
import org.springframework.data.jpa.repository.JpaRepository;

public interface TeamMemberRepository extends JpaRepository<TeamMember, Long> {

    // Check if a user is already a member of a team
    //how to view the query generated by this method?
    // You can enable SQL logging in Spring Boot to see the generated queries. Add the following line to your application.properties file:
    // spring.jpa.show-sql=true
    boolean existsByTeamIdAndUserId(Long teamId, Long id);

    boolean existsByTeamAndUserEmail(Team team, String email);


}
