spring.application.name=taskTracker
spring.datasource.url=jdbc:mysql://localhost:3306/tasktracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080

#what is the secret key for JWT token generation and expiration time in milliseconds
#secret key should be a long random string for security purposes
#secret key should be kept safe and not exposed in public repositories or client-side code
#expiration time should be set according to the needs of your application, for example, 3600000 milliseconds is equal to 1 hour
spring.jwt.secret=sivasubramaniyanRajapandiLovesDivyaPandSheLovesHimToo
spring.jwt.expiration=3600000


